// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CourseSpeedDepth.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "CourseSpeedDepth.h"

#include <ucdr/microcdr.h>
#include <string.h>

bool CourseSpeedDepth_serialize_topic(ucdrBuffer* writer, const CourseSpeedDepth* topic)
{
    bool success = true;

        success &= ucdr_serialize_float(writer, topic->course);

        success &= ucdr_serialize_float(writer, topic->speed);

        success &= ucdr_serialize_float(writer, topic->depth);

    return success && !writer->error;
}

bool CourseSpeedDepth_deserialize_topic(ucdrBuffer* reader, CourseSpeedDepth* topic)
{
    bool success = true;

        success &= ucdr_deserialize_float(reader, &topic->course);

        success &= ucdr_deserialize_float(reader, &topic->speed);

        success &= ucdr_deserialize_float(reader, &topic->depth);

    return success && !reader->error;
}

uint32_t CourseSpeedDepth_size_of_topic(const CourseSpeedDepth* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 4) + 4;

        size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}
