// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CourseSpeedDepthPublisher.c
 * Publisher example.
 *
 * This file was generated by the tool microxrceddsgen.
 */

#include "CourseSpeedDepth.h"

#include <uxr/client/client.h>
#include <ucdr/microcdr.h>
#include <math.h>
#include <stdlib.h>
#include <stdio.h>

#define STREAM_HISTORY  8
#define BUFFER_SIZE     UXR_CONFIG_UDP_TRANSPORT_MTU * STREAM_HISTORY


const char* participant_xml = "<dds>"
                                  "<participant>"
                                      "<rtps>"
                                          "<name>default_xrce_participant</name>"
                                      "</rtps>"
                                  "</participant>"
                              "</dds>";
const char* topic_xml = "<dds>"
                            "<topic>"
                                "<name>CourseSpeedDepthPubSubTopic</name>"
                                "<dataType>CourseSpeedDepth</dataType>"
                            "</topic>"
                        "</dds>";
const char* publisher_xml = "";
const char* datawriter_xml = "<dds>"
                                 "<data_writer>"
                                     "<topic>"
                                         "<kind>NO_KEY</kind>"
                                         "<name>CourseSpeedDepthPubSubTopic</name>"
                                         "<dataType>CourseSpeedDepth</dataType>"
                                     "</topic>"
                                 "</data_writer>"
                             "</dds>";

int main(int args, char** argv)
{

    // CLI
    if (3 > args || 0 == atoi(argv[2]))
    {
        printf("usage: program [-h | --help] | ip port [<max_topics>]\n");
        return 0;
    }

    char* ip = argv[1];
    char* port = argv[2];
    uint32_t max_topics = (args == 4) ? (uint32_t)atoi(argv[3]) : UINT32_MAX;

        // Transport
    uxrUDPTransport transport;
    if (!uxr_init_udp_transport(&transport, UXR_IPv4, ip, port))
    {
        printf("Error at create transport.\n");
        return 1;
    }

    // Session
    uxrSession session;
    uxr_init_session(&session, &transport.comm, 0xAAAABBBB);
    if(!uxr_create_session(&session))
    {
        printf("Error at create session.\n");
        return 1;
    }

    // Streams
    uint8_t output_reliable_stream_buffer[BUFFER_SIZE];
    uxrStreamId reliable_out = uxr_create_output_reliable_stream(&session, output_reliable_stream_buffer, BUFFER_SIZE, STREAM_HISTORY);

    uint8_t input_reliable_stream_buffer[BUFFER_SIZE];
    uxr_create_input_reliable_stream(&session, input_reliable_stream_buffer, BUFFER_SIZE, STREAM_HISTORY);

    // Create entities
    uxrObjectId participant_id = uxr_object_id(0x01, UXR_PARTICIPANT_ID);
    uint16_t participant_req = uxr_buffer_create_participant_xml(&session, reliable_out, participant_id, 0, participant_xml, UXR_REPLACE);

    uxrObjectId topic_id = uxr_object_id(0x02, UXR_TOPIC_ID);
    uint16_t topic_req = uxr_buffer_create_topic_xml(&session, reliable_out, topic_id, participant_id, topic_xml, UXR_REPLACE);

    uxrObjectId publisher_id = uxr_object_id(0x02, UXR_PUBLISHER_ID);
    uint16_t publisher_req = uxr_buffer_create_publisher_xml(&session, reliable_out, publisher_id, participant_id, publisher_xml, UXR_REPLACE);

    uxrObjectId datawriter_id = uxr_object_id(0x02, UXR_DATAWRITER_ID);
    uint16_t datawriter_req = uxr_buffer_create_datawriter_xml(&session, reliable_out, datawriter_id, publisher_id, datawriter_xml, UXR_REPLACE);

    // Send create entities message and wait its status
    uint8_t status[4];
    uint16_t requests[4] = {participant_req, topic_req, publisher_req, datawriter_req};
    if(!uxr_run_session_until_all_status(&session, 1000, requests, status, 4))
    {
        printf("Error at create entities: participant: %i topic: %i publisher: %i darawriter: %i\n", status[0], status[1], status[2], status[3]);
        return 1;
    }

    float course = 1;
    float speed = 2.8;
    float depth = 7.2;

    srand(time(NULL));

    // Write topics
    while(true)
    {
        // Decrease values gradually when reaching certain points
        if (course >= 20) course -= 0.1;
        if (speed >= 24.7) speed -= 0.1;
        if (depth >= 50) depth -= 0.1;

        // Adjust values to stay within specified ranges
        if (course <= 1) course = 1;
        if (speed <= 2.0) speed = 2.0;
        if (depth <= 5) depth = 5;

        // Round values to one decimal point
        course = roundf(course * 10) / 10;
        speed = roundf(speed * 10) / 10;
        depth = roundf(depth * 10) / 10;

        // Generate random increments
        float course_increment = (float)(rand() % 3 + 1) / 10; // Random increment between 0.1 and 0.3
        float speed_increment = (float)(rand() % 2 + 1) / 10;  // Random increment between 0.1 and 0.2
        float depth_increment = (float)(rand() % 2 + 1) / 10;  // Random increment between 0.1 and 0.2

        // Create the topic with adjusted values
        CourseSpeedDepth topic = {course, speed, depth};

        ucdrBuffer mb;
        uint32_t topic_size = CourseSpeedDepth_size_of_topic(&topic, 0);
        topic.course = course;
        topic.speed = speed;
        topic.depth = depth;
        uxr_prepare_output_stream(&session, reliable_out, datawriter_id, &mb, topic_size);
        CourseSpeedDepth_serialize_topic(&mb, &topic);
        printf("Sent course: %f, speed: %f, depth: %f\n", topic.course, topic.speed, topic.depth);

        // Increment values
        course += course_increment;
        speed += speed_increment;
        depth += depth_increment;

        // Send and wait one second
        uxr_run_session_time(&session, 1000);
    }


    // Delete resources
    uxr_delete_session(&session);

    return 0;
}